# Generated by Django 4.2.7 on 2023-12-06 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MFRE_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFRE_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(default='Building Name N/A', max_length=300)),
                ('dealName', models.CharField(default='Building Name N/A', max_length=120)),
                ('locationDescription', models.BooleanField(default=False)),
                ('numApartmentUnits', models.IntegerField(default=0)),
                ('parkingSpotsPerUnit', models.IntegerField(default=0)),
                ('rentableToGrossSqFtRatio', models.IntegerField(default=0)),
                ('acquisitionDate', models.DateField(default='2000-01-01')),
                ('goingInCapRate', models.FloatField(default=0.0)),
                ('acquisitionPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('exitDate', models.DateField(default='2000-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanToValue', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddField(
            model_name='mfre_model',
            name='tranches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MFRE_model.tranche'),
        ),
    ]
