# Generated by Django 4.2.7 on 2023-12-20 03:34

import MFRE_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFRE_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFRE_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(default='Building Name N/A', max_length=300)),
                ('dealName', models.CharField(default='Building Name N/A', max_length=120)),
                ('locationDescription', models.TextField(max_length=500)),
                ('numParkingSpots', models.IntegerField(default=0)),
                ('numApartmentUnits', models.IntegerField(default=0)),
                ('rentableToGrossSqFtRatio', models.IntegerField(default=0)),
                ('acquisitionDate', models.DateField(default='2000-01-01')),
                ('goingInCapRate', models.FloatField(default=0.0)),
                ('acquisitionPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('exitDate', models.DateField(default='2000-01-01')),
                ('parkingSpotsPerUnit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tranche', MFRE_model.models.Tranche(default=None, loanToValue=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
