# Generated by Django 4.2.7 on 2023-12-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFRE_model', '0002_mfre_model_tranche_delete_todo_mfre_model_tranches'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfre_model',
            name='numParkingSpots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mfre_model',
            name='parkingSpotsPerUnit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
