# Generated by Django 4.2.7 on 2023-12-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFRE_model', '0002_mfre_model_delete_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mfre_model',
            old_name='completed',
            new_name='locationDescription',
        ),
        migrations.RemoveField(
            model_name='mfre_model',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mfre_model',
            name='title',
        ),
        migrations.AddField(
            model_name='mfre_model',
            name='buildingName',
            field=models.CharField(default='Building Name N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='mfre_model',
            name='dealName',
            field=models.CharField(default='Building Name N/A', max_length=120),
        ),
    ]
