# Generated by Django 4.2.7 on 2023-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFRE_model', '0003_rename_completed_mfre_model_locationdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfre_model',
            name='numApartmentUnits',
            field=models.IntegerField(default=0),
        ),
    ]
