# Generated by Django 4.2.7 on 2023-12-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFRE_model', '0003_mfre_model_numparkingspots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfre_model',
            name='locationDescription',
            field=models.TextField(max_length=500),
        ),
    ]
