# Generated by Django 4.2.7 on 2023-12-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFRE_model', '0004_mfre_model_numapartmentunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfre_model',
            name='acquisitionDate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='mfre_model',
            name='acquistionPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='mfre_model',
            name='exitDate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='mfre_model',
            name='goingInCapRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mfre_model',
            name='parkingSpotsPerUnit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mfre_model',
            name='rentableToGrossSqFtRatio',
            field=models.IntegerField(default=0),
        ),
    ]
